### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Raghu9t2** [shivamshukla12/SAP-CAP#1]
![image](https://github.com/shivamshukla12/SAP-CAP/assets/47977436/3b5176e7-7cfc-456e-9d78-7b9c6a9807b8)

Facing issue when I clone the project from repository

**Comment by shivamshukla12** [comment]
Hi  @Raghu9t2  , this is not coming at my end -- tried to clone this repo and this worked , and i checked this is a public repo with no restriction almost. i checked this issue on Stackoverflow may be you can take a look at ----

https://stackoverflow.com/questions/23885449/unable-to-resolve-unable-to-get-local-issuer-certificate-using-git-on-windows

**Comment by Raghu9t2** [comment]
Thanks Shivam...Above thread helped in closing the issue I faced.
